### ISSUE TITLE
Redo DSU to store things properly and show held amount in the ResourceCounter

### ISSUE THREAD

**Issue by mipen** [mipen/Mechanical-Defence-2#10]

**Comment by Moumix3** [comment]
Adding the suggestion from user "Undecided" on the forums, regarding the issue with Silver, Gold and Uranium which aren't counted as "x20" for DSU storage capacities:

"I'd like to maybe see a DSU version for holding small items with a much larger cap than the normal 2250 for storing gold, silver, and similar "small" items. Maybe call it a vault or something? It would be easy enough to modify an existing DSU, up the cap, and restrict the item list to only gold and silver."

**Comment by mipen** [comment]
Done!
