### ISSUE TITLE
Droids fail to fight fires

### ISSUE THREAD

**Issue by Reznoriam** [mipen/Mechanical-Defence-2#11]
Myself and a friend are both encountering an issue wherein droids will not attempt to put out fires and will continue to wander aimlessly as if they had no work during an event. 

Rimworld Version 0.9.727

Mods
Cybernetic Storm v3.4
EdBPrepareCarefully v1.7.2
Mechanical Defense 2 Update 4
Modular Tables v1.43

**Comment by Reznoriam** [comment]
My apologies, but I don't seem to have the ability to add proper labels to this issue.

**Comment by mipen** [comment]
Oh, I assumed anyone could add labels. That's okay though :) thanks for letting me know about this! It looks like the update to Alpha 9 caused some problems. I've just fixed this and it'll be in the next update :)
