### ISSUE TITLE
[Bug] Droids regenerate injuries very fast 

### ISSUE THREAD

**Issue by angstr0m** [mipen/Mechanical-Defence-2#12]
Description of the issue:
Basic combat droids will heal injuries that don't destroy a body part outright almost immediately. This makes them almost invincible. 

I think the issue may be related to the constant high rest they are receiving.

Reproduction:
Send an unarmed and unarmored basic combat droid into a group of raiders. Given enough time it will kill all raiders. When fighting against mechanoids, the combat droid may get some body parts shot off, but it will also eventually kill all mechanoids.

**Comment by Moumix3** [comment]
As an addition to this bug, when inactive, a droid's parts will have greatly enhanced HP on each of their body parts (500/30 for example), and being hurt will actually result in them being "Enhanced" on that part for ludicrous % of efficiency. This disappears as soon as you activate the droid again though, so nothing gamebreaking => see images attached

![ss 2015-03-09 at 09 36 54](https://cloud.githubusercontent.com/assets/11393498/6564970/919a8a34-c6a4-11e4-9bf9-e6699ab5948d.jpg)

![ss 2015-03-09 at 09 40 21](https://cloud.githubusercontent.com/assets/11393498/6565011/f01e8c18-c6a4-11e4-9ed9-3f8f00568fae.jpg)

**Comment by Moumix3** [comment]
Issue tested and confirmed on vanilla game with only Mechanical Defense 2 - Version 5 installed.

**Comment by mipen** [comment]
This problem should now be fixed =]
