### ISSUE TITLE
Droids not recognizing controller jobs

### ISSUE THREAD

**Issue by Reznoriam** [mipen/Mechanical-Defence-2#13]
Droids all have the controller job checked, but fail to complete tasks when there are devices that need to be toggled. As a workaround, you can still select a job and prioritize the task.

I'm experimenting with a lone survivor scenario which includes only one human with the rest of the workforce consisting of droids as an experiment. In this scenario, the human is not available to toggle devices.

**Comment by Moumix3** [comment]
Issue tested and confirmed on vanilla game with only Mechanical Defense 2 - Version 5 installed.

**Comment by mipen** [comment]
Thanks for letting me know, I assumed the toggle job would come under hauling for some reason xD I've added it in properly now.
