### ISSUE TITLE
Droids will automatically disable their Draft mode

### ISSUE THREAD

**Issue by Moumix3** [mipen/Mechanical-Defence-2#15]
After a while, a Drafted droid will automatically go back to non-Drafted mode without user interaction.

I've mainly seen that with idle droids, but that may be happening with droids actively doing something (I don't think so, but it's hard to test).

Tested with all 9 kinds of droids, they all break free of Draft Mode.

**Comment by Moumix3** [comment]
Tested on vanilla game with only Mechanical Defense 2 - Version 5 installed.

**Comment by Reznoriam** [comment]
I believe that this is an intentional feature. Given that a droid will explode if it's batteries are depleted, if one was left on guard duty indefinitely it would eventually detonate. I believe you can station one on a droid charge pad, but I haven't tested it.

**Comment by Moumix3** [comment]
I can understand that, but that would be user error if they exploded for that reason. This is also happening with droids drafted and ordered to stand on a charging station, they will undraft and wander to a gathering point even if at full charge.

**Comment by mipen** [comment]
This is actually a vanilla feature, normal colonists will do the same. I can disable it if you would like however

**Comment by Moumix3** [comment]
If it's a vanilla feature/bug, it's not yours to fix. ;)
