### ISSUE TITLE
Crematorius Droids wearing a personal shield will lose all their UI

### ISSUE THREAD

**Issue by Moumix3** [mipen/Mechanical-Defence-2#16]
This happened with all droids back in Version 4 if I'm not mistaken, but it seems to have been fixed for all the droids, except Crematorius which still has that issue.

The "Health" and "Gear" tab along with the bottom order bar disappear as soon as a Crematorius droid wears a personal shield.

**Comment by Moumix3** [comment]
Tested on vanilla game with only Mechanical Defense 2 - Version 5 installed.

Not tested with other mods' shields, but I know the issue seemed to happen with all shields previously.

**Comment by mipen** [comment]
Thanks, fixed now =] It was a silly singular word that caused it ... :P
