### ISSUE TITLE
Droids spawner items have no value

### ISSUE THREAD

**Issue by Moumix3** [mipen/Mechanical-Defence-2#18]
The droids spawner items have no value set, which isn't an issue per se in the vanilla game, but is an issue with the "Prepare carefully" mod, where you can get one droid for 0.2 point, which is kind of breaking the balance (a lot!). :)

![ss 2015-03-09 at 10 33 11](https://cloud.githubusercontent.com/assets/11393498/6565943/4815b21e-c6ac-11e4-9a02-bccb2f4e4906.jpg)

**Comment by mipen** [comment]
Thanks for pointing this out, I've set the price at 1000. Do you think this is a good price? Should I go higher or lower?

**Comment by Moumix3** [comment]
I personally tried 1500 and 750, so your 1000 is around what I thought they were worth. :+1:
