### ISSUE TITLE
[Suggestion] Add more ways to get charcoal

### ISSUE THREAD

**Issue by Moumix3** [mipen/Mechanical-Defence-2#20]
Right now, there is only one way to get coal, and it might be a bit counter intuitive to have access to the coal burner before you can actually get that coal with an ore extractor.

I have two suggestions around that, one has been posted by Canute on the Ludeon forums:

- Workbench to create charcoal from wood (=> or add a recipe to the Electric smelter?)
- Add coal as an ore that can spawn in the world, just as Steel, Plasteel, etc...

**Comment by mipen** [comment]
I've added a recipe to the electric smelter which makes charcoal which can be used by the coal burner :)
