### ISSUE TITLE
[Suggestion] Randomize Extractor Output Time

### ISSUE THREAD

**Issue by Reznoriam** [mipen/Mechanical-Defence-2#21]
As it is right now, all extractors output on exactly the same tick. I was wondering if it would be an interesting idea to pick a random number at the time the map loads between 0 and the cycle time of an extractor. Therefore, all extractors would be outputting randomly which would make a more consistent stream of ore rather than there being a rush of work all at once.

This may be a stupid idea, but I thought it was worth consideration. Please feel free to comment everyone.

**Comment by mipen** [comment]
Done!
