### ISSUE TITLE
[Enhancement] Droid Naming Scheme

### ISSUE THREAD

**Issue by TehJoE** [mipen/Mechanical-Defence-2#4]
Currently, all Droids are named "Droid". For users of EdB's Interface mod, this can lead to an unnecessarily confusing colonist bar:

![Confusing bar](http://puu.sh/fB9lb/84b16deb67.jpg)

Clearly, it is impossible to tell which Droid is which without selecting it or clothing them to indicate their type. The issue is further compounded by the game's tendency to reorder your bar whenever a saved game is loaded. This probably leads to some confusion for other users as well, but I can't think of any examples immediately.

The suggested solution is simple: name the Droid after its type. (e.g. A Logistic Droid would be named *Logistic Droid*, a Combat Droid would be named *Combat Droid*, etc.) A further enhancement may be to allow players to name the Droids themselves, but this is unnecessary.

I would implement this myself and submit a pull request but it appears this must be done in the dll file, for which no source code is available on this repository.

**Comment by mipen** [comment]
Thanks for the suggestion :) I've added the type of droid as it's name

**Comment by mipen** [comment]
Oh, and the source code is available, just click on my name and it should show up

**Comment by TehJoE** [comment]
Wonderful! Thanks for the tip, didn't notice it was a separate repository :+1:
